In [ ]:
import mlflow
import mlflow.sklearn

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.sklearn.autolog()

data_diabetes = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(data_diabetes.data, data_diabetes.target)

with mlflow.start_run():
    reg = RandomForestRegressor(n_estimators=100, max_depth=20, max_features=10)
    reg.fit(X_train, y_train)

    predictions = reg.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)
    mlflow.log_metric("mse", mse)
    mlflow.log_metric("r2", r2)

2025/07/10 18:39:59 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during sklearn autologging: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to .\mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`


In [4]:
predictions

array([111.61907108, 198.28204964, 134.74911547, 155.78365972,
       165.83294951, 200.1927657 , 252.42146526, 179.57390988,
        78.69806248, 152.18333478, 155.41523224, 156.90808969,
       173.7142654 , 201.76758838, 114.95548558,  82.36822607,
       126.02507439,  85.93469798,  84.94108015, 222.01951343,
       227.02037037, 197.16068279, 168.1402615 , 180.26851095,
        94.85871452, 188.78980904, 163.64283761,  95.38577772,
       213.9556687 ,  93.06321997, 105.76762777, 132.78418391,
       118.76474454, 199.42836094,  84.43328965, 128.30930298,
        90.98324483, 199.86380628, 199.65836934, 138.43816068,
       145.66793651, 145.62544611, 196.13220922, 223.78875999,
       232.98143465, 111.03171797, 103.2257619 , 230.94199484,
       164.69633689, 211.42554004,  90.13432281, 132.39929389,
       152.0918182 , 199.47035254, 173.42286962,  91.05052548,
        70.01034969, 187.38974567,  79.96738207, 167.75749159,
        93.60388934, 129.44202342, 177.29999228, 187.22

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [2]:
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.concatenate([a, b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [5]:
print(np.vstack([a, b]))

[[1 2 3]
 [4 5 6]]


In [6]:
np.concatenate([a, b], axis=0)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.concatenate([a, b], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1